version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    image: pioneerfromussr/nodejsapp
    restart: unless-stopped
    env_file: .env
    environment:
      - author=$AUTHOR
      - uuid=$UUID
    ports:
      - "3000-3002:8000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    healthcheck: 
      test: "curl -f http://0.0.0.0:8000/status"
      interval: 30s
      timeout: 1m
      retries: 2
      
networks:
  app-network:
    driver: bridge
    
volumes:
  node_modules:
